INSERT INTO "library".articles (title,path_to) VALUES
('Уровень жизни населения.docx','src/main/resources/doc/'),
('Уголовная ответственность несовершеннолетних за совершение преступлений, связанных с наркотиками.docx','src/main/resources/doc/'),
('Торговые роботы Forex.docx','src/main/resources/doc/'),
('Способы выражения авторской позиции в произведение Дикая охота Короля Стаха.docx','src/main/resources/doc/'),
('Смарт-контракт как перспективный способ организации договорных отношений в Республике Беларусь.docx','src/main/resources/doc/'),
('Роль игровых механик при выводе онлайн-продукта на международный рынок.docx','src/main/resources/doc/'),
('Процентная политика банков в Республике Беларусь.docx','src/main/resources/doc/'),
('Проблема защиты прав осужденных.docx','src/main/resources/doc/'),
('Применение СУБД Oracle в экономике.docx','src/main/resources/doc/'),
('Особенности употребления фразеологических единиц в английских газетных текстах.docx','src/main/resources/doc/'),
('Незаконное производство абортов.docx','src/main/resources/doc/'),
('Научный потенциал Республики Беларусь.docx','src/main/resources/doc/'),
('Концептуальное моделирование политического дискурса.docx','src/main/resources/doc/'),
('Контроль средств массовой информации.docx','src/main/resources/doc/'),
('Защита экономических баз данных.docx','src/main/resources/doc/'),
('Государственная поддержка научно-технической инновационной деятельности в сфере малого и среднего бизнеса.docx','src/main/resources/doc/'),
('Внешний долг Республики Беларусь.docx','src/main/resources/doc/'),
('Аргументы против смертной казни.docx','src/main/resources/doc/');